name: gotchaped
region: nyc
services:
  - name: web
    image:
      registry_type: DOCR
      repository: gotchaped
      tag: latest
    http_port: 8080
    instance_size_slug: professional-xs
    instance_count: 1
    health_check:
      http_path: /
      port: 8080
    envs:
      - key: HOST
        value: "0.0.0.0"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${inpi-pg.DATABASE_URL}
databases:
  - name: inpi-pg
    engine: PG
    cluster_name: inpi-pg
    production: true
